import type { Metadata } from 'next'
import { ArrowRight, BadgeCheck, Globe2, Languages, Megaphone, ShieldCheck, Users } from 'lucide-react'
import { E2P_LINKS } from '@/lib/e2p-links'

export const metadata: Metadata = { title: 'KOL & Ambassador Network | E2PDAO', description: 'Apply to the E2PDAO KOL and Ambassador network through the private W3Claw intake.', alternates: { canonical: '/influence/' }, openGraph: { title: 'E2PDAO KOL & Ambassador Network', description: 'Creator assessment and market cooperation across Web3 communities.', url: '/influence/' } }

const CAPABILITIES = [
  { icon: Globe2, title: 'Regional coverage', text: 'Match creators and Ambassadors by country, market context and audience geography.' },
  { icon: Languages, title: 'Language fit', text: 'Coordinate native-language content and community communication across target markets.' },
  { icon: Megaphone, title: 'Campaign fit', text: 'Evaluate channels, content type, cooperation preferences and available performance evidence.' },
  { icon: ShieldCheck, title: 'Private review', text: 'Applications remain private until reviewed and are never automatically added to a public directory.' },
]

export default function InfluencePage(){return <div className="min-h-screen bg-web3-dark"><section className="border-b border-white/5 py-20 grid-bg"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-4xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">KOL & Ambassador Network</div><h1 className="mt-4 text-4xl font-bold text-white md:text-6xl">Build trusted relationships across <span className="text-web3-accent glow-text">markets and communities</span></h1><p className="mt-6 max-w-3xl font-mono text-sm leading-7 text-gray-400">E2PDAO evaluates creator channels, audience fit, regional capability and cooperation preferences before matching resources with suitable projects.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><a href={E2P_LINKS.kol('kol_network_hero')} className="inline-flex items-center justify-center gap-2 rounded bg-web3-accent px-7 py-4 text-xs font-bold uppercase tracking-widest text-black">Apply as a KOL <ArrowRight className="h-4 w-4"/></a><a href={E2P_LINKS.ambassador('kol_network_hero')} className="inline-flex items-center justify-center gap-2 rounded border border-web3-purple px-7 py-4 text-xs font-bold uppercase tracking-widest text-web3-purple">Apply as an Ambassador</a></div></div></div></section>
<section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{CAPABILITIES.map(item=><div key={item.title} className="rounded-xl border border-white/5 bg-web3-card p-6"><item.icon className="h-6 w-6 text-web3-accent"/><h2 className="mt-5 text-lg font-bold text-white">{item.title}</h2><p className="mt-3 font-mono text-xs leading-6 text-gray-400">{item.text}</p></div>)}</div></div></section>
<section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="rounded-xl border border-white/10 bg-web3-dark p-8"><BadgeCheck className="h-7 w-7 text-web3-accent"/><h2 className="mt-5 text-2xl font-bold text-white">KOL application</h2><p className="mt-4 font-mono text-xs leading-6 text-gray-400">For creators operating on X, Telegram, YouTube, TikTok and other relevant channels. Submit audience, language, region, rates and optional performance evidence.</p><p className="mt-5 font-mono text-[10px] leading-5 text-gray-600">Applicant-provided reach and performance data remain marked as self-reported until verified.</p><a href={E2P_LINKS.kol('kol_application_section')} className="mt-7 inline-flex items-center gap-2 font-mono text-xs font-bold uppercase tracking-widest text-web3-accent">Open KOL application <ArrowRight className="h-4 w-4"/></a></div><div className="rounded-xl border border-white/10 bg-web3-dark p-8"><Users className="h-7 w-7 text-web3-purple"/><h2 className="mt-5 text-2xl font-bold text-white">Ambassador application</h2><p className="mt-4 font-mono text-xs leading-6 text-gray-400">For regional operators with local market experience, community management, event organization or content capabilities.</p><p className="mt-5 font-mono text-[10px] leading-5 text-gray-600">Ambassadors share the creator resource library but are reviewed and labeled separately.</p><a href={E2P_LINKS.ambassador('ambassador_application_section')} className="mt-7 inline-flex items-center gap-2 font-mono text-xs font-bold uppercase tracking-widest text-web3-purple">Open Ambassador application <ArrowRight className="h-4 w-4"/></a></div></div></section>
<section className="py-20"><div className="container mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-white">E2PDAO × W3Claw</h2><p className="mx-auto mt-4 max-w-2xl font-mono text-sm leading-7 text-gray-400">Applications open in the jointly branded intake experience and are written directly to the private E2PDAO Owner resource library in W3Claw. E2PDAO does not maintain a duplicate application database on this website.</p></div></section></div>}
