import type { Metadata } from 'next'
import { ArrowRight, BarChart3, Building2, CheckCircle2, ClipboardList, Megaphone, Users } from 'lucide-react'
import PartnershipCards from '@/components/PartnershipCards'
import { E2P_LINKS } from '@/lib/e2p-links'

export const metadata: Metadata = { title: 'Web3 Growth, Listing & KOL Services | E2PDAO', description: 'Explore E2PDAO project growth, listing BD, KOL and Ambassador cooperation services.', alternates: { canonical: '/services/' }, openGraph: { title: 'E2PDAO Services', description: 'Structured Web3 growth, listing and creator cooperation.', url: '/services/' } }

const GROUPS = [
  { icon: BarChart3, title: 'Project Growth', intro: 'For Web3 teams preparing a launch, entering a new market or improving user acquisition.', items: ['Market positioning and growth diagnosis','KOL portfolio and content campaign planning','Community activities and user-growth coordination','Campaign data collection and review'] },
  { icon: Building2, title: 'Listing & BD Support', intro: 'For projects that need a clearer path through exchange requirements and market-entry preparation.', items: ['Project information and readiness diagnosis','Exchange standards and materials checklist','Target exchange and cooperation-path recommendations','BD resource coordination and process follow-up'] },
  { icon: Megaphone, title: 'KOL & Ambassador Cooperation', intro: 'For creators and regional operators seeking structured, longer-term Web3 cooperation.', items: ['Creator profile assessment and cooperation matching','Regional, language and community capability matching','Content brief, scheduling and cooperation records','Conversion and ROI tracking when campaign data is available'] },
]

export default function ServicesPage(){return <div className="min-h-screen bg-web3-dark"><section className="border-b border-white/5 py-20 grid-bg"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-4xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Services</div><h1 className="mt-4 text-4xl font-bold text-white md:text-6xl">Clear deliverables for <span className="text-web3-accent glow-text">market cooperation</span></h1><p className="mt-6 max-w-3xl font-mono text-sm leading-7 text-gray-400">E2PDAO evaluates each request before recommending resources, scope or cooperation terms. Specific exchange conditions and private partner rates are not published.</p><a href={E2P_LINKS.project('services_hero')} className="mt-8 inline-flex items-center gap-2 rounded bg-web3-accent px-7 py-4 text-xs font-bold uppercase tracking-widest text-black">Request a project evaluation <ArrowRight className="h-4 w-4"/></a></div></div></section>
<section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="space-y-8">{GROUPS.map(group=><article key={group.title} className="grid gap-8 rounded-2xl border border-white/10 bg-web3-card p-7 md:grid-cols-[0.75fr_1.25fr] md:p-10"><div><group.icon className="h-7 w-7 text-web3-accent"/><h2 className="mt-5 text-2xl font-bold text-white">{group.title}</h2><p className="mt-4 font-mono text-xs leading-6 text-gray-400">{group.intro}</p></div><div className="grid gap-3 sm:grid-cols-2">{group.items.map(item=><div key={item} className="flex items-start gap-3 rounded-lg border border-white/5 bg-black/30 p-4 font-mono text-xs leading-5 text-gray-300"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-web3-purple"/>{item}</div>)}</div></article>)}</div></div></section>
<section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div><ClipboardList className="h-7 w-7 text-web3-purple"/><h2 className="mt-5 text-3xl font-bold text-white">What happens after submission</h2><p className="mt-4 font-mono text-sm leading-7 text-gray-400">Your information enters the E2PDAO Owner workspace in W3Claw, where it is checked for completeness, duplication and cooperation fit. Submission does not guarantee approval, contact, listing or commercial results.</p></div><div className="space-y-3">{['Privately routed to the correct business library','Applicant-provided claims remain marked as unverified until reviewed','Owner reviews, edits and follows up in W3Claw','No private keys, seed phrases or exchange passwords are requested'].map(item=><div key={item} className="flex gap-3 rounded-lg border border-white/5 bg-web3-dark p-4 font-mono text-xs text-gray-300"><CheckCircle2 className="h-4 w-4 shrink-0 text-web3-accent"/>{item}</div>)}</div></div></div></section>
<section className="py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-9"><h2 className="text-3xl font-bold text-white">Choose a cooperation type</h2><p className="mt-3 font-mono text-xs text-gray-400">Select the option that best describes your role. Community members should join E2P Club directly.</p></div><PartnershipCards source="services_bottom"/></div></section></div>}
