import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, BarChart3, BookOpen, Bot, MessageCircle, ShieldCheck, Users } from 'lucide-react'
import { E2P_LINKS } from '@/lib/e2p-links'

export const metadata: Metadata = { title: 'E2P Club | Web3 Market Community', description: 'Join the E2PDAO Telegram community for public market discussion, education and ecosystem updates.', alternates: { canonical: '/club/' }, openGraph: { title: 'E2P Club', description: 'An open Web3 community for market learning.', url: '/club/' } }

const AREAS = [
  { icon: BarChart3, title: 'Market discussion', text: 'Community conversation around market structure, macro events and risk-aware trading.' },
  { icon: BookOpen, title: 'Education', text: 'Learning resources, research perspectives and practical risk-management concepts.' },
  { icon: Users, title: 'E2P updates', text: 'Public project, partnership and ecosystem updates shared with the community.' },
]

export default function ClubPage(){return <div className="min-h-screen bg-web3-dark"><section className="border-b border-white/5 py-20 grid-bg"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-4xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-purple">E2P Club</div><h1 className="mt-4 text-4xl font-bold text-white md:text-6xl">An open community for <span className="text-web3-purple glow-text">market learning</span></h1><p className="mt-6 max-w-3xl font-mono text-sm leading-7 text-gray-400">Join E2P Club for public market discussion, educational content and ecosystem updates. Community members do not need to submit an application.</p><a href={E2P_LINKS.telegram} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 rounded bg-web3-purple px-7 py-4 text-xs font-bold uppercase tracking-widest text-white">Join Telegram Community <ArrowRight className="h-4 w-4"/></a></div></div></section>
<section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-6 md:grid-cols-3">{AREAS.map(area=><div key={area.title} className="rounded-xl border border-white/5 bg-web3-card p-7"><area.icon className="h-6 w-6 text-web3-purple"/><h2 className="mt-5 text-xl font-bold text-white">{area.title}</h2><p className="mt-3 font-mono text-xs leading-6 text-gray-400">{area.text}</p></div>)}</div></div></section>
<section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto grid max-w-6xl gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><Bot className="h-7 w-7 text-web3-accent"/><h2 className="mt-5 text-3xl font-bold text-white">Trading Agent</h2><p className="mt-4 font-mono text-sm leading-7 text-gray-400">The Trading Agent is presented as a separate product module with its own live application. Review its operating model and risk boundaries before leaving the E2PDAO website.</p><Link href="/trading-agent" className="mt-7 inline-flex items-center gap-2 font-mono text-xs font-bold uppercase tracking-widest text-web3-accent">View Trading Agent introduction <ArrowRight className="h-4 w-4"/></Link></div><div className="rounded-xl border border-yellow-400/15 bg-yellow-400/5 p-7"><ShieldCheck className="h-6 w-6 text-yellow-300"/><h3 className="mt-4 text-lg font-bold text-white">Risk comes first</h3><p className="mt-3 font-mono text-xs leading-6 text-yellow-100/60">Community content and automated tools do not constitute financial advice. Cryptocurrency trading can result in total loss. No return, win rate or future performance is guaranteed.</p></div></div></section></div>}
