import type { Metadata } from "next";
import { ArrowRight, Ban, BookOpen, Bot, ChartCandlestick, CircleStop, Eye, FileText, Gauge, KeyRound, LockKeyhole, MessageSquare, Radar, Scale, ShieldCheck, Target, Users } from "lucide-react";
import { E2P_LINKS } from "@/lib/e2p-links";

export const metadata: Metadata = { title:"E2P Trading Agent | Think First. Trade Second.", description:"An AI trading decision system built around structured plans, hard risk gates and auditable review.", alternates:{canonical:"/club/"} };
const CONTRACT="0x597716022fc149c2b89061d6ec6b5eac4a97bc20";
const TERMINAL_CANDLES=[34,48,42,57,50,68,59,78,66,84,74,92,81,103,91,112,100,121,108,135,119,145,130,151,138,163,149,170,158,181,168,192];

function Terminal(){return <div className="v4-agent-terminal">
  <header><span>E2P / DECISION TERMINAL</span><span><i/> SYSTEM HEALTHY · OBSERVE MODE</span><span>BTCUSDT · 1H</span></header>
  <div className="v4-agent-terminal-grid">
    <section><small>AGENT DECISION</small><strong>WAIT</strong><h4>Edge insufficient.</h4><div><span>RISK STATE</span><b>PASSIVE</b><p>No order can be placed until context, reward-to-risk and event gates align.</p></div></section>
    <article><header><span>MARKET CONTEXT / BTCUSDT</span><span>1H · LIVE STRUCTURE</span></header><div className="v4-agent-chart">{TERMINAL_CANDLES.map((height,index)=><i key={index} className={index%5===0||index%7===0?"down":""} style={{height}}/>)}<span/><em>RESISTANCE · 68,420</em><span className="vwap"/><em className="vwap">VWAP · 67,880</em><span className="support"/><em className="support">HTF SUPPORT · 66,950</em></div><div className="v4-agent-metrics"><span><small>TREND</small><b>Mixed</b></span><span><small>CONFIDENCE</small><b>62%</b></span><span><small>R:R</small><b>1.2 : 1</b></span><span><small>EVENT RISK</small><b>HIGH · 1H 42M</b></span></div><footer><small>AGENT NOTE</small><p>Price is holding support, but remains below VWAP with event risk approaching. Preserve capital. Reassess after volatility resolves.</p></footer></article>
  </div>
  <footer><span>ILLUSTRATIVE — NOT A LIVE SIGNAL</span><span>DECISION ID · E2P-0826-1942</span></footer>
</div>}

export default function ClubPage(){return <>
  <section className="v4-agent-hero"><div className="v4-wrap v4-agent-hero-grid"><div><span className="v4-kicker">E2P Trading Agent</span><h1>Think first.<br/>Trade second<span>.</span></h1><p>The E2P Trading Agent transforms market context into structured trade plans, passes hard risk gates, acts only within narrow permissions and creates an auditable record.</p><small>ILLUSTRATIVE — NOT A LIVE SIGNAL</small></div><Terminal/></div></section>

  <section className="v4-agent-case"><div className="v4-wrap"><header><h2>A valid setup can<br/>still be a bad trade.</h2><p>We prove it before we pull the trigger.</p></header><div><span>PRE-TRADE CASE / ILLUSTRATIVE</span><section><article><small>THE SETUP</small><p>✓ Price at higher timeframe support</p><p>✓ Bullish divergence on RSI</p><p>✓ Liquidity sweep beneath lows</p><p>✓ Volume picking up</p></article><article><small>THE PROBLEM</small><p>× Trend against direction</p><p>× Below VWAP</p><p>× Event risk within 2 hours (FOMC)</p><p>× Unfavorable R:R</p></article><article className="verdict"><small>VERDICT</small><strong>NO TRADE</strong><p>Edge insufficient.<br/>Discipline is the edge.</p></article></section></div></div></section>

  <section id="agent-loop" className="v4-agent-loop"><div className="v4-wrap"><h2>The E2P Trading Agent loop</h2><div>{[{icon:Eye,title:"Observe",text:"Continuously scan market, macro, flow and project signals."},{icon:Radar,title:"Build context",text:"Synthesize multi-timeframe context and identify potential edges."},{icon:FileText,title:"Structure plan",text:"Define thesis, entry, invalidation, stop, size and monitoring."},{icon:ShieldCheck,title:"Pass risk",text:"Run the plan through hard pre-trade and system-health gates."},{icon:Target,title:"Act in scope",text:"Only approved instruments, size, permissions and rules."},{icon:BookOpen,title:"Review",text:"Record outcomes, rationale, execution quality and lessons."}].map((item,index)=><article key={item.title}><i>0{index+1}</i><div><item.icon size={25}/></div><h3>{item.title}</h3><p>{item.text}</p>{index<5&&<ArrowRight/>}</article>)}</div></div></section>

  <section className="v4-agent-modes"><div className="v4-wrap"><header><span className="v4-label">Operating modes</span><h2>You choose the mode.<br/>The Agent follows the rules.</h2></header><div><article><Eye/><h3>Observe</h3><p>Full context and decisions. No orders placed.</p><b>Best for learning and due diligence.</b></article><article><FileText/><h3>Paper</h3><p>Simulates orders with real-time rules. No capital at risk.</p><b>Best for validating strategies.</b></article><article><ShieldCheck/><h3>Controlled Live</h3><p>Live execution within strict permissions and risk limits.</p><b>Capital at risk. Start small.</b></article></div><p className="v4-agent-mode-note">You stay in control. You can pause, change mode, or revoke permissions at any time.</p></div></section>

  <section id="risk" className="v4-agent-risk"><div className="v4-wrap"><header><span className="v4-label">Risk constitution</span><h2>Risk before action.</h2></header><div>{[{icon:Scale,title:"Capital first",text:"Protect capital above all else. Survival is the edge."},{icon:LockKeyhole,title:"Pre-defined risk",text:"Maximum risk per idea. Maximum daily loss. Maximum open risk. Non-negotiable."},{icon:Ban,title:"Hard risk gates",text:"No order if any gate fails. No overrides. No exceptions."},{icon:Gauge,title:"Scope bound",text:"Only allowed instruments. Only allowed timeframes. Only allowed strategies."},{icon:FileText,title:"Auditable by design",text:"Every decision, action and change is recorded. You own the logs."}].map((item)=><article key={item.title}><item.icon size={25}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><strong>The Agent does not chase. The Agent does not guess. The Agent follows the constitution.</strong></div></section>

  <section id="community" className="v4-agent-community"><div className="v4-wrap"><header><span className="v4-label">Community intelligence</span><h2>Better context.<br/>Better decisions.<br/>Together.</h2></header><div>{[{icon:Radar,title:"Research",text:"Community-sourced research, data, signals and market observations."},{icon:BookOpen,title:"Playbooks",text:"Shared frameworks, checklists and repeatable processes."},{icon:Users,title:"Review",text:"Plans and outcomes reviewed for quality, bias, risk and discipline."},{icon:MessageSquare,title:"Feedback",text:"Structured feedback improves the Agent, community and process."}].map((item)=><article key={item.title}><item.icon/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>

  <section id="points" className="v4-agent-points"><div className="v4-wrap"><header><span className="v4-label">$E2P coordination layer</span><h2>Points and coordination.<br/>Not an investment.</h2></header><div>{[{icon:Bot,title:"Contribute",text:"Share research, insights or tools that add value to the ecosystem."},{icon:ChartCandlestick,title:"Reputation",text:"Earn reputation for useful, high-signal contributions."},{icon:KeyRound,title:"Access",text:"Unlock higher access to data, tools and agent features."},{icon:Users,title:"Voice",text:"Help steer initiatives and protocol improvements."}].map((item,index)=><article key={item.title}><i>0{index+1}</i><div><item.icon/></div><h3>{item.title}</h3><p>{item.text}</p>{index<3&&<ArrowRight/>}</article>)}</div><aside><b>$E2P is for coordination.</b><span>Not a security</span><span>Not a share</span><span>Not a promise</span><span>Not for speculation</span></aside></div></section>

  <section className="v4-agent-disclosure"><div className="v4-wrap"><div><span>RISK DISCLOSURE</span><p>Trading and investing involve substantial risk of loss and are not suitable for every person. Agent outputs are analysis and decision support, not guaranteed profits or financial advice.</p></div><strong>Never risk more than you can afford to lose.</strong></div></section>
  <section className="v4-agent-launch"><div className="v4-wrap"><CircleStop/><h2>Launch Trading Agent</h2><a href={E2P_LINKS.tradingAgent} target="_blank" rel="noreferrer" className="v4-button v4-button-acid">Open Agent <ArrowRight size={15}/></a><a href={`https://bscscan.com/token/${CONTRACT}`} target="_blank" rel="noreferrer" className="v4-text-link">View $E2P contract</a></div></section>
</>}
