import type { Metadata } from "next";
import { ArrowRight, Handshake, Radar, RefreshCw, Search, ShieldCheck, Sprout, Target, Users } from "lucide-react";
import { E2P_LINKS } from "@/lib/e2p-links";

export const metadata: Metadata = { title:"About E2P DAO | Evidence to Execution", description:"E2P is one operating network connecting project quality, creator distribution and disciplined market intelligence.", alternates:{canonical:"/about/"} };

const PRINCIPLES=[
  {index:"01",title:"Evidence before opinion.",text:"Start with what can be checked. Test the assumptions, surface missing information and let evidence shape the decision.",tag:"VERIFY",icon:Search},
  {index:"02",title:"Ownership before handoff.",text:"Keep one accountable owner close to the work—from first brief to the next decision—so context and momentum stay intact.",tag:"OWN",icon:Handshake},
  {index:"03",title:"Risk before action.",text:"Define permissions, failure conditions and downside before action. A good plan is clear about what it will not do.",tag:"BOUND",icon:ShieldCheck},
  {index:"04",title:"Learning after every cycle.",text:"Review the outcome, record what changed and feed the lesson into the next operating cycle.",tag:"IMPROVE",icon:RefreshCw},
];

function AboutTriad(){return <div className="v4-about-triad"><i/><i/><i/><section><img src="/e2p-icon-transparent.svg" alt=""/><b>E2P</b><small>OPERATING<br/>NETWORK</small></section><article className="one"><Sprout/><b>Incubator</b><p>Build quality and create the path.</p></article><article className="two"><Users/><b>KOL Marketplace</b><p>Match trusted voices to real opportunities.</p></article><article className="three"><Radar/><b>Trading Agent</b><p>Turn context into risk-gated decisions.</p></article></div>}

export default function AboutPage(){return <>
  <section className="v4-about-hero"><div className="v4-wrap v4-about-hero-grid"><div><span className="v4-label">About E2P DAO</span><h1>Built for the<br/>hard part between<br/>ambition and <span>execution.</span></h1><p>E2P connects project quality, creator distribution and bounded AI trading in one operating network—so builders, creators and community members can move from evidence to accountable action.</p></div><AboutTriad/></div></section>

  <section className="v4-about-engines"><div className="v4-wrap"><header><h2>One network. Three operating engines.</h2><p>Each engine solves a clear job. Together they connect project readiness, creator-led growth and disciplined market intelligence.</p></header><div><article><i><Sprout/></i><span><b>Incubator</b><p>We diagnose listing gaps, improve project quality, design the route and coordinate exchange BD.</p></span></article><ArrowRight/><article><i><Users/></i><span><b>KOL Marketplace</b><p>We match project needs with creator resources and operate campaigns from brief through review.</p></span></article><ArrowRight/><article><i><Radar/></i><span><b>Trading Agent</b><p>We turn market context into structured plans, deterministic risk checks and controlled CEX execution.</p></span></article></div><footer>Evidence, decisions, actions and review strengthen the next cycle.</footer></div></section>

  <section id="principles" className="v8-about-principles"><div className="v4-wrap"><header><span className="v4-label">Operating principles</span><h2>Four rules for<br/>moving work forward.</h2><p>Simple enough to use every day. Strong enough to keep decisions accountable when the work gets complex.</p></header><div>{PRINCIPLES.map((item,index)=><article className={`principle-${index+1}`} key={item.title}><header><i>{item.index}</i><item.icon/></header><h3>{item.title}</h3><p>{item.text}</p><footer><span>{item.tag}</span><i/></footer></article>)}</div></div></section>

  <section id="cycle" className="v4-about-cycle"><div className="v4-wrap"><header><span className="v4-label">Our operating cycle</span><h2>A simple loop we run constantly.</h2><p>It keeps the work clear, decisions grounded and improvement compounding.</p></header><div><article><Search/><h3>Evidence</h3><p>Gather signals. Validate what is real.</p></article><ArrowRight/><article><Target/><h3>Decision</h3><p>Choose the path. Define constraints.</p></article><ArrowRight/><article><ArrowRight/><h3>Action</h3><p>Execute with focus. Respect the plan.</p></article><ArrowRight/><article><RefreshCw/><h3>Review</h3><p>Measure outcomes. Capture lessons.</p></article></div></div></section>

  <section id="participate" className="v4-about-participate"><div className="v4-wrap"><span className="v4-label">Ways to participate</span><div><a href={E2P_LINKS.project("about_project_v4")}><Sprout/><h3>Projects</h3><p>Teams can use the Incubator to strengthen project quality and prepare a credible exchange path.</p><ArrowRight/></a><a href={E2P_LINKS.kol("about_creator_v4")}><Users/><h3>Creators</h3><p>KOLs and creators can access aligned project opportunities, campaigns, events and longer-term roles.</p><ArrowRight/></a><a href={E2P_LINKS.partner("about_partner_v4")}><Handshake/><h3>Partners</h3><p>Operators, exchanges and service providers can collaborate through clear mandates and shared work.</p><ArrowRight/></a><a href={E2P_LINKS.telegram}><Radar/><h3>Community</h3><p>Contribute research, review and feedback around the token-based trading community.</p><ArrowRight/></a></div></div></section>

  <section className="v4-about-cta"><div className="v4-wrap"><h2>Build with E2P</h2><p>If you care about doing the work and doing it right, there is a place for you in the network.</p><a href={E2P_LINKS.project("about_final_v4")} className="v4-button v4-button-acid">Build with E2P <ArrowRight size={15}/></a></div></section>
</>}
