import type { Metadata } from "next";
import { ArrowRight, Handshake, LockKeyhole, MessageSquare, Radar, RefreshCw, Search, ShieldCheck, Sprout, Target, Users } from "lucide-react";
import { E2P_LINKS } from "@/lib/e2p-links";

export const metadata: Metadata = { title:"About E2P DAO | Evidence to Execution", description:"E2P is one operating network connecting project quality, creator distribution and disciplined market intelligence.", alternates:{canonical:"/about/"} };

const PRINCIPLES=[
  {index:"01",title:"Evidence before opinion.",text:"We start with facts, not narrative. Sources, assumptions and missing proof stay visible until verified.",visual:"evidence"},
  {index:"02",title:"Ownership before handoff.",text:"We stay close to the work. Clear accountability, visible progress and direct follow-up keep the next move alive.",visual:"ownership"},
  {index:"03",title:"Risk before action.",text:"We identify what can go wrong, define what must not happen and size every action inside explicit boundaries.",visual:"risk"},
  {index:"04",title:"Learning after every cycle.",text:"We review outcomes honestly, capture lessons and improve the operating system. Each cycle makes the next one stronger.",visual:"learning"},
];

function AboutTriad(){return <div className="v4-about-triad"><i/><i/><i/><section><img src="/e2p-icon-transparent.svg" alt=""/><b>E2P</b><small>DAO</small></section><article className="one"><Sprout/><b>Incubator</b><p>Turn ideas into validated market paths.</p></article><article className="two"><Users/><b>KOL Marketplace</b><p>Connect credible voices with aligned opportunity.</p></article><article className="three"><Radar/><b>Trading Agent</b><p>Operate decisions inside explicit risk controls.</p></article></div>}

export default function AboutPage(){return <>
  <section className="v4-about-hero"><div className="v4-wrap v4-about-hero-grid"><div><span className="v4-label">About E2P DAO</span><h1>Built for the<br/>hard part between<br/>ambition and <span>execution.</span></h1><p>E2P exists to turn real ideas into measurable movement. We connect project quality, distribution and decision infrastructure in one operating network.</p></div><AboutTriad/></div></section>

  <section className="v4-about-engines"><div className="v4-wrap"><header><h2>One network. Three operating engines.</h2><p>Each engine solves a clear job. Together they create a closed loop from opportunity to outcome—and back again.</p></header><div><article><i><Sprout/></i><span><b>Incubator</b><p>Strengthen the project and prepare the right market route.</p></span></article><ArrowRight/><article><i><Users/></i><span><b>KOL Marketplace</b><p>Match credible creators with aligned campaigns and opportunities.</p></span></article><ArrowRight/><article><i><Radar/></i><span><b>Trading Agent</b><p>Turn market context into disciplined, auditable decisions.</p></span></article></div><footer>Insights and outcomes feed the next cycle.</footer></div></section>

  <section className="v4-about-principles"><div className="v4-wrap"><span className="v4-label">Operating principles</span><div>{PRINCIPLES.map((item)=><article key={item.title}><i>{item.index}</i><section><h2>{item.title}</h2><p>{item.text}</p></section><div className={`v4-principle-visual ${item.visual}`}>{item.visual==="evidence"?<><Search/><span>VERIFY THE SOURCE</span></>:item.visual==="ownership"?<><img src="/people/team-collaboration.jpg" alt="Collaborative operating team"/><ArrowRight/></>:item.visual==="risk"?<><i/><i/><ShieldCheck/><span>DEFINE THE BOUNDARY</span></>:<><RefreshCw/><span>REVIEW → LEARN → IMPROVE</span></>}</div></article>)}</div></div></section>

  <section className="v4-about-cycle"><div className="v4-wrap"><header><span className="v4-label">Our operating cycle</span><h2>A simple loop we run constantly.</h2><p>It keeps the work clear, decisions grounded and improvement compounding.</p></header><div><article><Search/><h3>Evidence</h3><p>Gather signals. Validate what is real.</p></article><ArrowRight/><article><Target/><h3>Decision</h3><p>Choose the path. Define constraints.</p></article><ArrowRight/><article><ArrowRight/><h3>Action</h3><p>Execute with focus. Respect the plan.</p></article><ArrowRight/><article><RefreshCw/><h3>Review</h3><p>Measure outcomes. Capture lessons.</p></article></div></div></section>

  <section className="v4-about-standards"><div className="v4-wrap"><span className="v4-label">Our standards and commitments</span><div><article><MessageSquare/><h3>Truthful claims</h3><p>No misleading promises. Uncertainty stays visible.</p></article><article><Handshake/><h3>Protected relationships</h3><p>Private contacts, commercial context and trust stay protected.</p></article><article><LockKeyhole/><h3>Narrow permissions</h3><p>Access is granted by need and controlled by design.</p></article><article><ShieldCheck/><h3>Measurable work</h3><p>Success is defined before the work and reviewed honestly.</p></article></div></div></section>

  <section className="v4-about-participate"><div className="v4-wrap"><span className="v4-label">Ways to participate</span><div><a href={E2P_LINKS.project("about_project_v4")}><Sprout/><h3>Projects</h3><p>Diagnose, improve and prepare the next market move.</p><ArrowRight/></a><a href={E2P_LINKS.kol("about_creator_v4")}><Users/><h3>Creators</h3><p>Find aligned projects, partnerships and opportunities.</p><ArrowRight/></a><a href={E2P_LINKS.partner("about_partner_v4")}><Handshake/><h3>Partners</h3><p>Collaborate through clear mandates and shared outcomes.</p><ArrowRight/></a><a href={E2P_LINKS.telegram}><Radar/><h3>Community</h3><p>Share feedback and improve every operating cycle.</p><ArrowRight/></a></div></div></section>

  <section className="v4-about-cta"><div className="v4-wrap"><h2>Build with E2P</h2><p>If you care about doing the work and doing it right, there is a place for you in the network.</p><a href={E2P_LINKS.project("about_final_v4")} className="v4-button v4-button-acid">Build with E2P <ArrowRight size={15}/></a></div></section>
</>}
