import Link from 'next/link'
import { ArrowRight, BarChart3, Building2, CheckCircle2, ClipboardCheck, Megaphone, Search, Users } from 'lucide-react'
import Hero from '@/components/Hero'
import PartnershipCards from '@/components/PartnershipCards'
import { E2P_LINKS } from '@/lib/e2p-links'

const SERVICES = [
  { icon: BarChart3, title: 'Project Growth', text: 'Market positioning, growth diagnosis, KOL campaign design, community activation and performance review.' },
  { icon: Building2, title: 'Listing & BD Support', text: 'Project material review, exchange requirement mapping, target-path recommendations and process follow-up.' },
  { icon: Megaphone, title: 'KOL & Ambassador Network', text: 'Creator assessment, regional matching, content briefs, cooperation scheduling and longer-term relationship building.' },
]

const PROCESS = [
  ['01','Apply','Choose the cooperation type and submit structured information through W3Claw.'],
  ['02','Evaluate','E2PDAO reviews completeness, fit, public signals and potential duplication.'],
  ['03','Propose','Qualified applicants receive a tailored cooperation path, scope and next steps.'],
  ['04','Execute','Approved parties coordinate briefs, resources, timelines and accountable delivery.'],
  ['05','Review','Results, open items and future opportunities are recorded for follow-up.'],
]

export default function HomePage() {
  return <>
    <Hero/>
    <section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Core Services</div><h2 className="mt-3 text-3xl font-bold text-white md:text-5xl">Three paths to market</h2><p className="mt-4 font-mono text-sm leading-6 text-gray-400">Clear deliverables for projects, creators and professional partners—without exposing private rates or internal cooperation terms.</p></div><div className="mt-10 grid gap-6 md:grid-cols-3">{SERVICES.map(service=><div key={service.title} className="rounded-xl border border-white/5 bg-web3-card p-7"><service.icon className="h-6 w-6 text-web3-accent"/><h3 className="mt-5 text-xl font-bold text-white">{service.title}</h3><p className="mt-3 font-mono text-xs leading-6 text-gray-400">{service.text}</p></div>)}</div><Link href="/services" className="mt-8 inline-flex items-center gap-2 font-mono text-xs font-bold uppercase tracking-widest text-web3-accent">View service deliverables <ArrowRight className="h-4 w-4"/></Link></div></section>

    <section className="border-b border-white/5 bg-web3-card/35 py-20 grid-bg"><div className="container mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-purple">Why E2PDAO</div><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">Operator-led cooperation</h2><p className="mt-5 font-mono text-sm leading-7 text-gray-400">E2PDAO combines exchange operations experience, Web3 growth execution, creator relationships and a trading-oriented community. Cooperation starts with fit and evidence—not generic reach promises.</p><div className="mt-7 space-y-3">{['Structured application and evaluation','Resource matching by market and objective','Private business records handled through W3Claw','Clear separation between verified facts and applicant-provided data'].map(item=><div key={item} className="flex gap-3 font-mono text-xs text-gray-300"><CheckCircle2 className="h-4 w-4 shrink-0 text-web3-purple"/>{item}</div>)}</div></div><div className="rounded-xl border border-white/10 bg-web3-dark p-7"><div className="flex items-center gap-3 border-b border-white/10 pb-4"><ClipboardCheck className="h-5 w-5 text-web3-accent"/><span className="font-mono text-[10px] font-bold uppercase tracking-widest text-gray-400">Operating background</span></div><div className="mt-6 space-y-5 font-mono text-xs">{[['2018','Exchange futures operations'],['2020','TRON ecosystem DeFi operations'],['2021','KOL creator network development'],['2022','E2PDAO growth and listing network'],['Now','Structured project, KOL and partner collaboration']].map(([year,text])=><div key={year} className="flex gap-4"><span className="w-12 shrink-0 font-bold text-web3-accent">{year}</span><span className="text-gray-400">{text}</span></div>)}</div></div></div></section>

    <section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="text-center"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Cooperation Process</div><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">From application to review</h2></div><div className="mt-10 grid gap-4 md:grid-cols-5">{PROCESS.map(([step,title,text])=><div key={step} className="rounded-xl border border-white/5 bg-web3-card p-5"><span className="font-mono text-xs font-bold text-web3-accent">{step}</span><h3 className="mt-4 text-base font-bold text-white">{title}</h3><p className="mt-3 font-mono text-[10px] leading-5 text-gray-500">{text}</p></div>)}</div></div></section>

    <section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-purple">Verified Work</div><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">Evidence before promises</h2></div><Link href="/success-cases" className="inline-flex items-center gap-2 font-mono text-xs font-bold uppercase tracking-widest text-web3-accent">View success cases <ArrowRight className="h-4 w-4"/></Link></div><div className="mt-9 grid gap-5 md:grid-cols-3">{[['CHAX','CEX listing coordination','Public market reference available'],['HIRO','Listing readiness and coordination','Public market reference available'],['Virtuals Protocol','Circulating supply verification support','Public CMC reference available']].map(([name,work,proof])=><div key={name} className="rounded-xl border border-white/10 bg-web3-dark p-6"><h3 className="text-xl font-bold text-white">{name}</h3><p className="mt-3 font-mono text-xs text-gray-400">{work}</p><p className="mt-5 border-t border-white/5 pt-4 font-mono text-[9px] uppercase tracking-widest text-web3-accent">{proof}</p></div>)}</div></div></section>

    <section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Choose Your Path</div><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">Four cooperation types, one intake system</h2><p className="mt-4 font-mono text-sm leading-6 text-gray-400">Applications open in the E2PDAO-branded W3Claw intake and are privately routed to the correct business library.</p></div><div className="mt-10"><PartnershipCards source="home_partnerships"/></div></div></section>

    <section className="py-20 grid-bg"><div className="container mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8"><Users className="mx-auto h-8 w-8 text-web3-purple"/><h2 className="mt-5 text-3xl font-bold text-white">E2P Club is open to community members</h2><p className="mx-auto mt-4 max-w-2xl font-mono text-sm leading-6 text-gray-400">Join the public Telegram community for market discussion, education and E2P updates. No application form is required.</p><a href={E2P_LINKS.telegram} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 rounded bg-web3-purple px-7 py-4 text-xs font-bold uppercase tracking-widest text-white">Join E2P Club <ArrowRight className="h-4 w-4"/></a><p className="mt-8 font-mono text-[10px] leading-5 text-gray-600">E2PDAO does not guarantee listing, campaign outcomes, investment returns or token performance. Never submit private keys, seed phrases or exchange passwords.</p></div></section>
  </>
}
