import type { Metadata } from 'next'
import { ExternalLink, ShieldCheck } from 'lucide-react'
import { E2P_LINKS } from '@/lib/e2p-links'

export const metadata: Metadata = { title: 'Verified Success Cases | E2PDAO', description: 'Review public references for completed E2PDAO listing and market-support work.', alternates: { canonical: '/success-cases/' }, openGraph: { title: 'E2PDAO Success Cases', description: 'Public references for completed support.', url: '/success-cases/' } }

const CASES = [
  { project:'CHAX', category:'CEX Listing', result:'Listing support and market-entry coordination.', proof:'CoinGecko market reference', href:'https://www.coingecko.com/en/coins/chax' },
  { project:'HIRO', category:'CEX Listing', result:'Listing readiness, materials and exchange coordination.', proof:'CoinMarketCap market reference', href:'https://coinmarketcap.com/currencies/hiro/#Markets' },
  { project:'Virtuals Protocol', category:'CMC Support', result:'Circulating supply verification support.', proof:'CoinMarketCap public reference', href:'https://coinmarketcap.com/currencies/virtual-protocol/' },
  { project:'USBT', category:'Listing Advisory', result:'Listing advisory and intermediary coordination.', proof:'Gate.io public announcement', href:'https://www.gate.io/zh/announcements/article/39267' },
]

export default function SuccessCasesPage(){return <div className="min-h-screen bg-web3-dark"><section className="border-b border-white/5 py-20 grid-bg"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-4xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Success Cases</div><h1 className="mt-4 text-4xl font-bold text-white md:text-6xl">Public references for <span className="text-web3-accent glow-text">completed support</span></h1><p className="mt-6 max-w-3xl font-mono text-sm leading-7 text-gray-400">Only work with a public, verifiable reference is shown. Each project, scope and result should be interpreted within its original context.</p></div></div></section><section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-6 md:grid-cols-2">{CASES.map(item=><a key={item.project} href={item.href} target="_blank" rel="noopener noreferrer" className="group rounded-xl border border-white/10 bg-web3-card p-7 transition-colors hover:border-web3-accent/40"><div className="flex items-center justify-between"><span className="rounded bg-web3-accent/10 px-2 py-1 font-mono text-[9px] font-bold uppercase tracking-widest text-web3-accent">{item.category}</span><ExternalLink className="h-4 w-4 text-gray-600 group-hover:text-web3-accent"/></div><h2 className="mt-5 text-2xl font-bold text-white">{item.project}</h2><p className="mt-3 font-mono text-xs leading-6 text-gray-400">{item.result}</p><p className="mt-6 border-t border-white/5 pt-4 font-mono text-[9px] uppercase tracking-widest text-gray-500">Proof: {item.proof}</p></a>)}</div></div></section><section className="py-20"><div className="container mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8"><ShieldCheck className="mx-auto h-8 w-8 text-web3-purple"/><h2 className="mt-5 text-3xl font-bold text-white">Past support is not a future guarantee</h2><p className="mx-auto mt-4 max-w-2xl font-mono text-xs leading-6 text-gray-500">A listing, campaign or verification outcome depends on project quality, third-party decisions, market conditions and regulatory requirements.</p><a href={E2P_LINKS.project('success_cases_bottom')} className="mt-7 inline-flex items-center rounded bg-web3-accent px-7 py-4 text-xs font-bold uppercase tracking-widest text-black">Request a project evaluation</a></div></section></div>}
