import type { Metadata } from 'next'
import { ArrowRight, BadgeCheck, BarChart3, Coins, ExternalLink, Gift, Handshake, Megaphone, Network, ShieldCheck, Users } from 'lucide-react'
import { EcosystemOrbit, RingChart } from '@/components/EcosystemVisuals'

export const metadata: Metadata = { title: '$E2P Point | Contribution & Ecosystem Utility', description: 'Understand how E2P Point recognizes project, creator, Ambassador and community contribution.', alternates: { canonical: '/tokenomics/' }, openGraph: { title: '$E2P Point', description: 'The contribution and ecosystem utility layer of E2PDAO.', url: '/tokenomics/' } }

const CONTRACT = '0x597716022fc149c2b89061d6ec6b5eac4a97bc20'
const CONTRIBUTORS = [
  { icon: Handshake, role:'Project Scouts', action:'Introduce qualified projects and provide complete, useful context.', value:'Verified referral contribution' },
  { icon: Megaphone, role:'KOLs', action:'Deliver approved campaign work with evidence and accountable follow-up.', value:'Content and campaign contribution' },
  { icon: Network, role:'Ambassadors', action:'Support regional communities, local content and market activation.', value:'Regional growth contribution' },
  { icon: Users, role:'Club Members', action:'Participate in education, feedback, events and authorized community tasks.', value:'Community contribution' },
]
const RIGHTS = [
  ['Recognition','A visible contribution record and ecosystem reputation when the product layer is active.'],
  ['Access','Eligibility for selected events, research, campaigns or cooperation opportunities.'],
  ['Priority','Potential priority in reviewed campaigns, Ambassador programs and ecosystem initiatives.'],
  ['Governance','Future participation in defined community decisions, subject to published rules.'],
]
const STATUS = [
  ['Contribution framework','Defined','Roles and contribution categories are presented on this page.'],
  ['Public task ledger','Roadmap','Requires authenticated, verifiable records before launch.'],
  ['Point redemption','Roadmap','No fixed conversion or guaranteed monetary value is promised.'],
  ['On-chain $E2P token','Live contract','BEP-20 contract is publicly viewable on BscScan.'],
]

export default function TokenomicsPage(){return <div className="min-h-screen bg-web3-dark">
  <section className="border-b border-white/5 py-20 grid-bg"><div className="container mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:px-8"><div><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">$E2P Point</div><h1 className="mt-4 text-4xl font-bold text-white md:text-6xl">Recognize contribution across the <span className="text-web3-accent glow-text">E2P ecosystem</span></h1><p className="mt-6 max-w-3xl font-mono text-sm leading-7 text-gray-400">E2P Point is the contribution and access concept connecting projects, creators, Ambassadors and Club members. It should reward verifiable ecosystem value—not empty clicks or unverified activity.</p></div><div className="rounded-2xl border border-white/10 bg-web3-card/80 p-7"><div className="flex items-center gap-3 border-b border-white/10 pb-5"><Coins className="h-6 w-6 text-web3-accent"/><div><h2 className="text-base font-bold text-white">Point and Token are different layers</h2><p className="mt-1 font-mono text-[9px] uppercase tracking-widest text-gray-500">Contribution record ≠ guaranteed financial value</p></div></div><div className="mt-5 space-y-4"><div className="rounded-lg bg-black/30 p-4"><span className="font-mono text-[9px] font-bold uppercase tracking-widest text-web3-accent">E2P Point</span><p className="mt-2 font-mono text-xs leading-5 text-gray-400">Off-chain contribution, reputation and access framework. Product capabilities are introduced progressively.</p></div><div className="rounded-lg bg-black/30 p-4"><span className="font-mono text-[9px] font-bold uppercase tracking-widest text-web3-purple">$E2P Token</span><p className="mt-2 font-mono text-xs leading-5 text-gray-400">An existing BEP-20 asset. Holding it does not guarantee rewards, returns or access unless a specific rule is published.</p></div></div></div></div></section>

  <section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[1fr_0.8fr] lg:items-center lg:px-8"><EcosystemOrbit/><div><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-purple">Value Flow</div><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">Earn → Access → Contribute → Govern</h2><p className="mt-4 font-mono text-sm leading-7 text-gray-400">The visual model places $E2P at the center of Incubator, KOL, Club and AI Agent participation. Each connection requires a published rule and verifiable contribution record.</p><div className="mt-8 grid grid-cols-2 gap-4"><RingChart value={60} label="Community allocation" color="#00FF66" size="sm"/><RingChart value={40} label="Other allocation" color="#8A2BE2" size="sm"/></div><p className="mt-5 font-mono text-[9px] leading-5 text-gray-600">Allocation visualization reflects the existing 60% community / 40% combined treasury, team and advisor presentation.</p></div></div></section>

  <section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-purple">Contribution Paths</div><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">Four roles create ecosystem value</h2></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{CONTRIBUTORS.map(item=><div key={item.role} className="rounded-xl border border-white/10 bg-web3-card p-6"><item.icon className="h-6 w-6 text-web3-accent"/><h3 className="mt-5 text-lg font-bold text-white">{item.role}</h3><p className="mt-3 font-mono text-xs leading-6 text-gray-400">{item.action}</p><p className="mt-5 border-t border-white/5 pt-4 font-mono text-[9px] uppercase tracking-widest text-web3-purple">{item.value}</p></div>)}</div></div></section>

  <section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><Gift className="h-7 w-7 text-web3-purple"/><h2 className="mt-5 text-3xl font-bold text-white">Potential utility</h2><p className="mt-4 font-mono text-sm leading-7 text-gray-400">Utility is activated only when rules, verification and operational capacity are ready. The website does not promise a fixed cash value or conversion rate.</p></div><div className="grid gap-3 sm:grid-cols-2">{RIGHTS.map(([title,text])=><div key={title} className="rounded-xl border border-white/10 bg-web3-dark p-5"><h3 className="text-base font-bold text-white">{title}</h3><p className="mt-3 font-mono text-[10px] leading-5 text-gray-500">{text}</p></div>)}</div></div></section>

  <section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Product Status</div><h2 className="mt-3 text-3xl font-bold text-white">Live, defined and roadmap</h2></div><BarChart3 className="h-7 w-7 text-web3-accent"/></div><div className="mt-6 overflow-hidden rounded-xl border border-white/10">{STATUS.map(([feature,status,note],index)=><div key={feature} className={`grid gap-3 bg-web3-card p-5 md:grid-cols-[1fr_160px_1.5fr] ${index?'border-t border-white/5':''}`}><span className="text-sm font-bold text-white">{feature}</span><span className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">{status}</span><span className="font-mono text-[10px] leading-5 text-gray-500">{note}</span></div>)}</div></div></section>

  <section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-[1fr_auto] lg:items-center lg:px-8"><div><div className="flex items-center gap-3"><BadgeCheck className="h-6 w-6 text-web3-accent"/><h2 className="text-2xl font-bold text-white">On-chain $E2P reference</h2></div><p className="mt-4 break-all font-mono text-xs text-web3-accent">{CONTRACT}</p><p className="mt-3 font-mono text-[10px] leading-5 text-gray-500">BNB Smart Chain · BEP-20 · Verify contract details independently.</p></div><a href={`https://bscscan.com/token/${CONTRACT}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded border border-web3-accent px-6 py-4 text-xs font-bold uppercase tracking-widest text-web3-accent">View on BscScan <ExternalLink className="h-4 w-4"/></a></div></section>

  <section className="py-20"><div className="container mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8"><ShieldCheck className="mx-auto h-8 w-8 text-yellow-300"/><h2 className="mt-5 text-3xl font-bold text-white">Contribution is not an investment promise</h2><p className="mx-auto mt-4 max-w-2xl font-mono text-xs leading-6 text-gray-500">Points, tokens, access and future governance are separate concepts. No section of this page guarantees price, liquidity, yield, redemption or future utility.</p></div></section>
</div>}
