import type { Metadata } from 'next'
import { ArrowRight, CalendarDays, Megaphone, Target } from 'lucide-react'
import { E2P_LINKS } from '@/lib/e2p-links'

export const metadata: Metadata = { title: 'Web3 Campaign Cooperation | E2PDAO', description: 'Learn how E2PDAO structures KOL and Ambassador campaign cooperation.', alternates: { canonical: '/campaigns/' }, openGraph: { title: 'E2PDAO Campaign Cooperation', description: 'Structured briefs, resource matching and authorized participation.', url: '/campaigns/' } }

const CAMPAIGNS = [
  { title: 'Project launch campaign', status: 'Example format', objective: 'Awareness and qualified community growth around a launch milestone.', deliverables: 'KOL content, community activity and campaign review.' },
  { title: 'Regional Ambassador activation', status: 'Example format', objective: 'Local-language education, community engagement and offline or online activation.', deliverables: 'Regional content, community session and contribution record.' },
]

export default function CampaignsPage(){return <div className="min-h-screen bg-web3-dark"><section className="border-b border-white/5 py-20 grid-bg"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-4xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Campaign Cooperation</div><h1 className="mt-4 text-4xl font-bold text-white md:text-6xl">Structured briefs and <span className="text-web3-accent glow-text">authorized participation</span></h1><p className="mt-6 max-w-3xl font-mono text-sm leading-7 text-gray-400">E2PDAO coordinates project objectives, creator fit, content deliverables and review. Specific activity participation is handled through the corresponding public W3Claw activity page.</p><a href={E2P_LINKS.project('campaigns_hero')} className="mt-8 inline-flex items-center gap-2 rounded bg-web3-accent px-7 py-4 text-xs font-bold uppercase tracking-widest text-black">Discuss a project campaign <ArrowRight className="h-4 w-4"/></a></div></div></section>
<section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-9"><h2 className="text-3xl font-bold text-white">Published activity format</h2><p className="mt-3 font-mono text-xs text-gray-500">Only Owner-authorized activities with a real W3Claw public activity URL are published. The cards below demonstrate the approved information format and are not open for registration.</p></div><div className="grid gap-6 md:grid-cols-2">{CAMPAIGNS.map(item=><article key={item.title} className="rounded-xl border border-white/10 bg-web3-card p-7"><div className="flex items-center justify-between"><span className="rounded bg-web3-purple/10 px-2 py-1 font-mono text-[9px] uppercase tracking-widest text-web3-purple">{item.status}</span><CalendarDays className="h-4 w-4 text-gray-600"/></div><h2 className="mt-5 text-xl font-bold text-white">{item.title}</h2><div className="mt-5 space-y-4"><div><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-widest text-gray-600"><Target className="h-3 w-3"/>Objective</div><p className="mt-2 font-mono text-xs leading-5 text-gray-400">{item.objective}</p></div><div><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-widest text-gray-600"><Megaphone className="h-3 w-3"/>Deliverables</div><p className="mt-2 font-mono text-xs leading-5 text-gray-400">{item.deliverables}</p></div></div><div className="mt-6 rounded border border-white/5 bg-black/30 px-4 py-3 text-center font-mono text-[9px] uppercase tracking-widest text-gray-600">Example only · Registration closed</div></article>)}</div><p className="mt-6 rounded-lg border border-yellow-400/15 bg-yellow-400/5 p-4 font-mono text-[10px] leading-5 text-yellow-100/60">Campaign participation is never stored on the E2PDAO website. When an authorized campaign is active, its button links to the exact W3Claw `/airdrop/[slug]` public activity page.</p></div></section></div>}
