import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, Globe2, Megaphone, Radio, Target, Users } from 'lucide-react'
import { E2P_LINKS } from '@/lib/e2p-links'

export const metadata: Metadata = { title: 'Web3 Campaign Hub | E2PDAO', description: 'Explore E2PDAO KOL campaign formats, delivery workflow and measurement framework.', alternates: { canonical: '/campaigns/' }, openGraph: { title: 'E2PDAO Campaign Hub', description: 'KOL, community and regional campaign opportunities.', url: '/campaigns/' } }

const SNAPSHOT = [['4','Campaign formats'],['4','Core channels'],['6','Market regions'],['5','Delivery stages']]
const FORMATS = [
  { icon:Radio, title:'Launch Awareness', stage:'Pre-TGE / TGE', platforms:'X · Telegram · YouTube', goal:'Build narrative awareness and qualified community attention.' },
  { icon:Globe2, title:'Regional Expansion', stage:'Growth', platforms:'Local KOL · Ambassador', goal:'Enter a target market with native-language distribution and feedback.' },
  { icon:Users, title:'Community Activation', stage:'Product / Event', platforms:'Telegram · X · AMA', goal:'Turn awareness into participation, product education and community action.' },
  { icon:BarChart3, title:'Long-term Ambassador', stage:'Ongoing', platforms:'Multi-channel', goal:'Create consistent local presence instead of one-off promotion.' },
]
const PIPELINE = [
  ['01','Objective','Define the desired action: awareness, join, register, product use or event participation.'],
  ['02','Matrix','Select creator tiers, channels, markets, content formats and community touchpoints.'],
  ['03','Brief','Set narrative, mandatory facts, disclosure, timing and acceptance criteria.'],
  ['04','Delivery','Coordinate content review, publishing evidence and campaign status.'],
  ['05','Review','Compare reach, engagement, tracked actions, delivery quality and next-step learning.'],
]
const METRICS = ['Content delivered','Qualified reach','Engagement rate','Tracked clicks','Community joins','Registrations','Product actions','Cost per result']

export default function CampaignsPage(){return <div className="min-h-screen bg-web3-dark">
  <section className="border-b border-white/5 py-20 grid-bg"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-4xl"><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">Campaign Hub</div><h1 className="mt-4 text-4xl font-bold text-white md:text-6xl">Turn creator reach into a <span className="text-web3-accent glow-text">structured campaign</span></h1><p className="mt-6 max-w-3xl font-mono text-sm leading-7 text-gray-400">E2PDAO combines KOL content, Ambassador activation and Club touchpoints around one brief, one delivery process and a measurable review framework.</p><a href={E2P_LINKS.project('campaigns_hero')} className="mt-8 inline-flex items-center gap-2 rounded bg-web3-accent px-7 py-4 text-xs font-bold uppercase tracking-widest text-black">Plan a project campaign <ArrowRight className="h-4 w-4"/></a></div></div></section>

  <section className="border-b border-white/5 bg-web3-card/30 py-12"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{SNAPSHOT.map(([value,label])=><div key={label} className="rounded-xl border border-white/5 bg-web3-dark p-5"><div className="text-3xl font-bold text-white">{value}</div><div className="mt-1 font-mono text-[10px] font-bold uppercase tracking-widest text-web3-accent">{label}</div></div>)}</div></div></section>

  <section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="font-mono text-[10px] font-bold uppercase tracking-widest text-web3-purple">Opportunity Types</div><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">Campaigns matched to project stage</h2></div><Link href="/influence" className="inline-flex items-center gap-2 font-mono text-xs font-bold uppercase tracking-widest text-web3-accent">Explore KOL Network <ArrowRight className="h-4 w-4"/></Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{FORMATS.map(item=><article key={item.title} className="rounded-xl border border-white/10 bg-web3-card p-6"><div className="flex items-center justify-between"><item.icon className="h-6 w-6 text-web3-purple"/><span className="rounded bg-white/5 px-2 py-1 font-mono text-[9px] uppercase tracking-widest text-gray-500">{item.stage}</span></div><h3 className="mt-5 text-lg font-bold text-white">{item.title}</h3><p className="mt-3 font-mono text-xs leading-6 text-gray-400">{item.goal}</p><p className="mt-5 border-t border-white/5 pt-4 font-mono text-[9px] uppercase tracking-widest text-web3-accent">{item.platforms}</p></article>)}</div></div></section>

  <section className="border-b border-white/5 bg-web3-card/30 py-20"><div className="container mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.75fr_1.25fr] lg:px-8"><div><CalendarDays className="h-7 w-7 text-web3-accent"/><h2 className="mt-5 text-3xl font-bold text-white">One accountable pipeline</h2><p className="mt-4 font-mono text-sm leading-7 text-gray-400">Campaign participation is attached to a specific authorized activity. E2PDAO does not keep a fake public application counter or browser-only booking record.</p></div><div className="space-y-3">{PIPELINE.map(([step,title,text])=><div key={step} className="flex gap-4 rounded-xl border border-white/5 bg-web3-dark p-5"><span className="font-mono text-xs font-bold text-web3-accent">{step}</span><div><h3 className="text-sm font-bold text-white">{title}</h3><p className="mt-1 font-mono text-[10px] leading-5 text-gray-500">{text}</p></div></div>)}</div></div></section>

  <section className="border-b border-white/5 py-20"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div><Target className="h-7 w-7 text-web3-purple"/><h2 className="mt-5 text-3xl font-bold text-white">What a result report should show</h2><p className="mt-4 font-mono text-sm leading-7 text-gray-400">Results should use actual delivery and tracked actions. Page views alone are not a campaign outcome.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{METRICS.map(metric=><div key={metric} className="flex min-h-24 items-center justify-center rounded-xl border border-white/10 bg-web3-card p-4 text-center font-mono text-[10px] font-bold uppercase tracking-widest text-gray-400">{metric}</div>)}</div></div></div></section>

  <section className="py-20"><div className="container mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8"><Megaphone className="mx-auto h-8 w-8 text-web3-accent"/><h2 className="mt-5 text-3xl font-bold text-white">Live opportunities appear only when authorized</h2><p className="mx-auto mt-4 max-w-2xl font-mono text-xs leading-6 text-gray-500">An active campaign card will link to its exact W3Claw public activity page, where eligibility, deadline and participation are handled. No active campaign is fabricated for display.</p><div className="mt-7 inline-flex items-center gap-2 rounded border border-white/10 bg-web3-card px-5 py-3 font-mono text-[10px] uppercase tracking-widest text-gray-500"><CheckCircle2 className="h-4 w-4 text-web3-accent"/>Campaign feed ready for authorized listings</div></div></section>
</div>}
